<?php defined( '_SHM_ENABLED_' ) or die( 'Restricted access' ); ?>
<!-- begin:: Aside -->
<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
<div class="kt-aside kt-aside--fixed kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">
    <?php require_once("layout/_aside-brand.inc"); ?>
    <?php require_once("layout/_aside-menu.inc"); ?>
</div>
<!-- end:: Aside -->