<?php defined( '_SHM_ENABLED_' ) or die( 'Restricted access' ); ?>
<!-- begin:: Footer -->
<div class="kt-footer kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop">
    <div class="kt-footer__copyright">2019&nbsp;&copy;&nbsp;<a href="https://www.shortease.com/" target="_blank" class="kt-link">Shortease</a></div>
    <div class="kt-footer__menu">
    	<a href="https://www.shortease.com/about-2/" target="_blank" class="kt-footer__menu-link kt-link">About</a>
    	<a href="https://www.shortease.com/contact-us-1/" target="_blank" class="kt-footer__menu-link kt-link">Contact</a></div>
</div>
<!-- end:: Footer -->